---
title: "Predicting Life Expectancy"
author: "Venslaus Prakash Arokiaraj, Pushpit Saxena"
output:
  html_document: 
    theme: readable
    highlight: tango
    toc: yes
  pdf_document: default
urlcolor: dodgerblue
---

<style>
body {
text-align: justify}
</style>

***

# Team

- Name: **team_bbg**

- Size: **`2`**

- Details:

| Member Name                | Member NetId |
|----------------------------|--------------| 
| Pushpit Saxena             | `pushpit2`   |
| Venslaus Prakash Arokiaraj | `vpa2`       |

# Introduction

This project will mainly focus on studying different factors that play statistically significant role in influencing **Life Expectancy**. Some of the factors we will be focussing on are economic factors, social factors, health services factors (like immunizzation levels), mortality rate and various other health related factors. 

## Dataset Information

Based on the description of the dataset on [kaggle](https://www.kaggle.com/kumarajarshi/life-expectancy-who), the Global Health Observatory(**GHO**) data repository under World Health Organization (**WHO**) keeps track of the health status as well as many other related factors for all countries. The datasets are made available to public for the purpose of health data analysis. This datset was collected from WHO and United Nations website and then the individual data files have been combined into a single data set (read more [here](https://www.kaggle.com/kumarajarshi/life-expectancy-who#Description))

## Description

The dataset we will be using for this project is Life Expectancy data that can be found at [Life Expectancy (WHO)](https://www.kaggle.com/kumarajarshi/life-expectancy-who?select=Life+Expectancy+Data.csv). The dataset has 22 variables and  2939 observations which needs some cleanup. (*Note: we have also provided the dataset as part of the .zip [[`lifeExpectancyData`](lifeExpectancyData.csv)] that we have uploaded for this proposal*).

## Data fields

Following are some of the important variables used in this dataset:

- **`Country`** (String): Country of observation

- **`Year`** (Integer): Year of observation

- **`Status`** (String): Whether the country of observation is developed or developing.

- **`Life expectancy`** (Decimal): Life expectancy in age

- **`Adult Mortality`** (Integer): Adult Mortality Rates of both sexes (probability of dying between 15 and 60 years per 1000 population) 

- **`Infant deaths`** (Integer): Number of Infant Deaths per 1000 population

- **`Alcohol`** (Decimal): Alcohol, recorded per capita (15+) consumption (in litres of pure alcohol) 

- **`Percentage Expenditure`** (Decimal): Expenditure on health as a percentage of Gross Domestic Product per capita(%)

- **`Hepatitis B`** (Int): Hepatitis B (HepB) immunization coverage among 1-year-olds (%) 

- **`Measles`** (Int): Measles - number of reported cases per 1000 population 

- **`BMI`** (Decimal): Average Body Mass Index of entire population

- **`Under-five deaths`** (Int): Number of under-five deaths per 1000 population

- **`Polio`** (Int): Polio (Pol3) immunization coverage among 1-year-olds (%)

- **`Total expenditure`** (Decimal): General government expenditure on health as a percentage of total government expenditure (%)

- **`Diphtheria`** (Int): Diphtheria tetanus toxoid and pertussis (DTP3) immunization coverage among 1-year-olds (%)

- **`HIV/AIDS`** (Decimal): Deaths per 1 000 live births HIV/AIDS (0-4 years)

- **`GDP`** (Decimal): Gross Domestic Product per capita (in USD)

- **`Population`** (Int): Population of the country

## Goals of the model

- From the standpoint of our research and learning, one of the primary reason for us to pick this dataset, is the size as well as variety of predictors that are available. We believe that this dataset is perfect for us to practice and implement majority of the techniques we have learned as part of the course and get a hands-on experience on a real life dataset.

- From larger perspective of data exploration and using data science to address real world issues, this dataset gives us an opportunity to try and answer some of the most important questions the human race is facing, like various factors affecting the longevity of life. As we briefly mentioned in our project description, we are interested in determining different factors which contributes to lower the value of life expectancy. Particularly, in this dataset as the observations are based on different countries, if we are able to find a good model than we can answer questions like what a country needs to focus on in order to have better life expectancy.

# Methods

## Data Cleaning

Life Expectancy dataset was provided by WHO and it had lot of NA values. Hence the data had to be cleaned up in the following manner.

```{r}
library(gridExtra)
library(reshape2)
library(tidyverse)

# Reading the dataset
who = read.csv("LifeExpectancyData.csv")

# Original number of records
nrow(who)

# Data Cleanup
who = who %>% 
  drop_na() %>% 
  filter(!is.na(Life.expectancy), !is.na(Adult.Mortality), !is.na(infant.deaths))

# Number of records after data cleanup
nrow(who)
```


# Results

# Discussion

# Appendix


